version: '3'
services:
  # api:
  #   container_name: app-node-container
  #   build: .
  #   links:
  #     - database  
  #   depends_on:
  #     - database
  database:
    image: mongo:latest
    container_name: app-mongo-container
    volumes: 
      - './data/pokedex.jons:/app/data/pokedex.json'
    environment:
      - MONGO_DATABASE=database
      - MONGO_ROOT_USERNAME=root
      - MONGO_ROOT_PASSWORD=root
    expose:
      - 27017
    ports:
      - 27017:27017
volumes: 
  mongodb-data:      
# /!\ check container dependencies / depends_on + volumes
